### ISSUE TITLE
 vdl120.zip for latest release

### ISSUE THREAD

**Issue by aMark-home** [pappe82/Vdl120#1]
Can you please create a ' vdl120.zip' file for the latest release?

Or let me know how to create one from the source code.

BR,
Mark

**Comment by pappe82** [comment]
Hi Mark, I just added the zip file to the latest release. 
https://github.com/pappe82/Vdl120/releases/download/1.0.2302.901/vdl120.zip

Feel free to contact me again if you have troubles using the tool.

Also, if you want to build the sources yourself, you need Visual Studio 2022 with C# Development Workload.

**Comment by pappe82** [comment]
For now I close the issue.

**Comment by aMark-home** [comment]
That was quick. Thanks! :)
